### ISSUE TITLE
SDK2 avatars don't send any parameters via OSC

### ISSUE THREAD

**Issue by knah** [vrchat-community/osc#106]
**Describe the bug**
When using an SDK2 avatar, no parameters are sent via OSC at all.

**To Reproduce**
Just use any SDK2 avatar, move around/use gestures and observe complete lack of messages sent from VRChat.

**Expected behavior**
OSC messages are sent for default parameters, such as `GestureLeft`, `VelocityX` and other parameters present on all avatars by default.

**Info (please complete the following information):**
 - Type: PC/desktop mode
 - VRChat version and build w_2022.1.1p2 (build 1171)

**Additional context**
For the context, I wanted to make a VR overlay that shows currently used gesture regardless of used avatar - very useful for Index controllers where finger tracking is mildly unreliable and I can never know if I'm actually making Rock'n'Roll gesture or not. Unfortunately, with current state of OSC, it would only work on SDK3 avatars.

**Comment by slord399** [comment]
SDK2 is deprecated so it is intentional to be not supported.
Basically no more new feature. That's it.

**Comment by knah** [comment]
While I'm aware that SDK2 is deprecated and won't get any real new features, in-game support for them is still on the roadmap as far as I can tell - for example, the Dynamics beta has DynBone -> PhysBone converter working just fine on SDK2 avatars (well, as fine as it works in general).
I'd argue that this feature is similar to that in nature - something that is nice to have to keep all the existing SDK2 avatars at a usable level and not punish their users for wanting to stick with an old and beloved avatar.

**Comment by momo-the-monster** [comment]
SDK2 is deprecated and uses an entirely different system for setting parameters - our efforts here will be focused on improving and expanding OSC support for the current and future SDKs.
