### ISSUE TITLE
Launch parameter to disable game controller input

### ISSUE THREAD

**Issue by Naraenda** [vrchat-community/osc#122]
**What's the idea?**
I like to use a game controller (in my case a DDR DancePad) to control avatar parameters. However since it by default maps to controller inputs it also controls in game actions like jumping and (un)muting.

**Is there another way?**
As far as I know there isn't a way to disable a controller from within VRChat.

**Comment by mjcox244** [comment]
Can't you just, disable steam input
Or edit your steam input binds so map them all to an unused key

**Comment by Naraenda** [comment]
> Can't you just, disable steam input Or edit your steam input binds so map them all to an unused key

Disabling Steam Input doesn't work, even after restarting the game. Steam doesn't even recognize it as a valid controller. It only gets recognized by Windows. 

![image](https://user-images.githubusercontent.com/18581205/164563247-8291af8e-3d24-4cd2-bb1d-3cfbf69e1893.png)

**Comment by Naraenda** [comment]
I've found a program called [HidHide](https://github.com/ViGEm/HidHide) that allows me to exclude certain HIDDevices (and therefore controllers) to specific processes. I wouldn't say it's an ideal solution, but a work around for now.
