### ISSUE TITLE
Some Wiki Links Point to the Staging repo, 404ing

### ISSUE THREAD

**Issue by NarryG** [vrchat-community/osc#13]
Certain wiki pages contain hyperlinks which currently are pointed towards the staging repository and not this repository, resulting in a 404 on access.

Links I could locate: 
[https://github.com/vrchat-community/osc/wiki/Avatar-Parameters](https://github.com/vrchat-community/osc/wiki/Avatar-Parameters): vrc-emote.tosc points to staging

[https://github.com/vrchat-community/osc/wiki/Avatar-Parameters](https://github.com/vrchat-community/osc/wiki/Avatar-Parameters) example-avatar-config.json points to staging

[https://github.com/vrchat-community/osc/wiki/Input](https://github.com/vrchat-community/osc/wiki/Input) vrc-input.tosc points to staging

(There was no issue template for documentation)

**Comment by momo-the-monster** [comment]
Fixed, thank you!
