### ISSUE TITLE
OSC String

### ISSUE THREAD

**Issue by Romaxx** [vrchat-community/osc#132]
Add the ability to use string arguments with OSC :)

**Comment by benaclejames** [comment]
How would this be used? VRChat doesn't support string parameters and neither do unity animators

**Comment by EIA485** [comment]
while i too have no idea what this person is asking for looks like they do plan to support string parameters for chat boxes as seen in [this blog post](https://ask.vrchat.com/t/developer-update-11-august-2022/12286#text-chatbox-)

**Comment by Romaxx** [comment]
Yes I've seen that for chatboxes @EIA485, more easy to use than float/int string system like this: [https://github.com/killfrenzy96/KillFrenzyAvatarText](https://github.com/killfrenzy96/KillFrenzyAvatarText)

**Comment by momo-the-monster** [comment]
Closing this out, as we don't support Avatar String Parameters at all, and don't have plans for it afaik.
