### ISSUE TITLE
osc docs

### ISSUE THREAD

**Issue by EIA485** [vrchat-community/osc#138]
the[ vrchat osc documentation](https://docs.vrchat.com/docs/osc-overview) mentions nothing about the new chat box end points:
 `/chatbox/input s b` Input text into the chatbox. If b is True, send the text in s immediately, bypassing the keyboard. If b is False, open the keyboard and populate it with the provided text.
`/chatbox/typing b` Toggle the typing indicator on or off.

**Comment by asdfisdffdg** [comment]
it doesn't even seem to work...

**Comment by EIA485** [comment]
works for me, if your having trouble heres a list of trouble shooting steps: 
1- make sure osc is on, this option is in the raidial menu under options->osc
2- doable check you are sending to the correct port
3- check what data you are sending by using a program like [protokol](https://hexler.net/protokol)
the data from protokol should look something like
```
RECEIVE    | ENDPOINT([::ffff:127.0.0.1]:9001) ADDRESS(/chatbox/input) STRING(example string that auto sends) BOOL(TRUE)
RECEIVE    | ENDPOINT([::ffff:127.0.0.1]:9001) ADDRESS(/chatbox/input) STRING(example string that opens in the vrchat keyboard to be edited) BOOL(FALSE)
```

**Comment by asdfisdffdg** [comment]
NOW it works, last time I could send jump but chat didn't do anything. Maybe osc needs to be enabled when the game starts? 🤷

**Comment by momo-the-monster** [comment]
My apologies - I haven't been able to keep up the OSC docs and responses here as much as I would like. Updated now: [Chatbox](https://github.com/vrchat-community/osc/wiki/Chatbox)
