### ISSUE TITLE
OSCQuery release date ?

### ISSUE THREAD

**Issue by Romaxx** [vrchat-community/osc#143]
OSCQuery has been introduced in the September dev update but no news of it since this date.
Is implementation still planned ?

Thanks

**Comment by momo-the-monster** [comment]
It’s currently in closed beta, which is going well, I think. I expect it will advance to open bet rather soon.

**Comment by Romaxx** [comment]
Could it be possible to have some more informations about OSCQuery protocol for Vrchat ? I'm creating an app to link some devices to Vrchat using OSC protocol and the pooling method to find quest/computer IP is very archaic, I'm interrested to add mdns discovery to my app, is vrchat using "_oscjson._tcp." mdns service announcement or is it custom one ?

**Comment by momo-the-monster** [comment]
You can fill out this form to apply for the OSCQuery closed beta:
https://forms.gle/CknjEBD3FnxoJfr17

**Comment by momo-the-monster** [comment]
Oops, forgot to move this along - OSCQuery is [implemented in the client](https://docs.vrchat.com/docs/oscquery) as of release 2023.3.1.
