### ISSUE TITLE
Increase the expression parameter synced data limit beyond 128 bits

### ISSUE THREAD

**Issue by NGenesis** [vrchat-community/osc#15]
The current 128 bit limit on expression parameters is insufficient to allow for combined eye and face tracking with reasonable fidelity and needs to be signficantly increased to accommodate for this, especially if there is a desire to add more functionality to an avatar on top of face and eye tracking.

[Edited to remove content which violates VRChat's TOS]

**Comment by Codel1417** [comment]
I think this would be more appropriate for a canny post. https://feedback.vrchat.com/

**Comment by regzo2** [comment]
I just want to add some context to this, the mod allows you to set every facial tracking parameter to a 'Binary' parameter version, which essentially acts as a lower resolution float parameter. This does allow you to get nearly full facial tracking with some space to spare. So there is definitely some ways to compact parameters to be able to fit all face tracking parameters.

Would be nice to have some extra expression parameters, or even a dedicated parameter list for facial tracking!

**Comment by momo-the-monster** [comment]
Hm - if the 'problem to solve' here is to enable high-fidelity eye and face tracking, then we aim to tackle that as part of the Avatar Face Control milestone, which I've attached to this issue.

**Comment by AeroScripts** [comment]
There are many use cases for more than 128 bits worth of parameters, face tracking needs it too for sure, but this is more of a fundamental enhancement that would open up a lot of doors for general OSC stuff too

**Comment by momo-the-monster** [comment]
@AeroScripts I agree. There still needs to be some limit, but we'll consider raising it with the work we're doing on Avatars this year.

**Comment by alexderpyfox** [comment]
For multiple other reasons this would be nice to have especially when you got an avatar like the rexouim which got 38 face blendshapes and also a couple of eye ones it would really add more to realism

**Comment by alexderpyfox** [comment]
Raise it to 512 bits sounds reasonable

**Comment by Dervali-git** [comment]
256bit would be great, 512 amazing, but yes. the limit needs to be increased with OSC and dynamics around the corner

**Comment by anonmon** [comment]
256 bits (Only 32 total floats/integers with room for nothing else) would be a nice bump, but still within "Could conceivably easily run out of parameters." depending on what we're trying to do.
512 bits (64 total floats/integers with no room for anything else) is the point where we genuinely have enough space to practically never run out of bits for anything. Unless we're straight up trying to replicate every body joint's rotation with floats or something equally insane.
Most people who don't need more than a few toggles for clothes and such are fine with the low current limit, but people who want to do actually cool things need _a lot_ more than we have now.
Also more IK networked slots would be nice/crucial along with a bump in total number.

**Comment by A3yuu** [comment]
I want an extra bit for fingers.
Unity has 20 parameters on the finger, so 40 Float (320 bits) is needed on the left and right, but now there are only 16.
Oculus is capable of finger Skeleton Tracking, and SteamVR has a Full Skeleton Input level.

**Comment by seanedwards** [comment]
While the VRChat team is considering this proposal, I've written up a doc describing a technique for effectively getting more parameters out of the same number of bits. OSC unlocks this technique in a way that wasn't viable before. Hopefully it's helpful to some folks who are anxious for this. https://github.com/seanedwards/vrc-worldobject/blob/main/docs/parameter-multiplexing.md (Pull requests welcome as always!)

**Comment by momo-the-monster** [comment]
Now doubled to 256!
