### ISSUE TITLE
osc endpoint to control eye gaze direction on any avatar

### ISSUE THREAD

**Issue by EIA485** [vrchat-community/osc#16]
### Discussed in https://github.com/vrchat-community/osc/discussions/12

<div type='discussions-op-text'>

<sup>Originally posted by **EIA485** February 16, 2022</sup>
currently if i want to implement eye tracking via osc id need to do it using parameters. this would require per avatar set up. would love to have some generalized osc endpoints for the eye gaze direction and eye openness.</div>

**Comment by Shadowriver** [comment]
I +1 that, setting up avatar with animation hack for this is a pain, this would make things way easier and it would be more future proof if native eye tracking support would been implemented. Ability to disable pseudo eye tracking that is already there would be good too.

**Comment by Shadowriver** [comment]
OSC going live let me notice extra argument for this, current eye tracking hacks on avatars requires custom animations which also requires unbinding eyes, which means eye tracking is blocked by safty settings and require other user to lift it while eye tracking is harmless, by gaze which is supervised it will make eye tracking visible without need of asking to lift safty.

**Comment by EIA485** [comment]
oops looks like this issue never got closed. this was implemented in version [2023.2.1, build 1295](https://docs.vrchat.com/docs/vrchat-202321). [link to the docs](https://docs.vrchat.com/docs/osc-eye-tracking) for anyone interested.
