### ISSUE TITLE
More than one OSC device connection/OSC messages out from client from avatar

### ISSUE THREAD

**Issue by PointDevice** [vrchat-community/osc#17]
Im not the absolutely most experienced with OSC, while i have played with it in the past with some of my personal projects

the biggest use that i personally see with using OSC on an avatar is to have peripherals, the first idea that comes to mind is say an avatar has a couple of held objects, irl, i wear a rig of buttons in areas where those items would be attached that send signals to equip and de-eqiup said items.

the problem comes in when i want to use something like mouth tracking with this, or anything else

my understanding of OSC is that the sender is supposed to point at the receiver and that is it, but my experience is that both needed static IPs configured to remain consistent to my liking, im not sure if that is correct, or maybe i had something else wrong, as mentioned my experience with the protocol is very limited.  so my question is, am i going about this the wrong way and it wont be an issue/is this just going to be supported and not be an issue?

---------------------------------
the second question is more of a request, sending messages to an avatar gives us a lot as is, as logic for input and UI stuff can be offloaded to a custom app, or something pre-made like touchOSC, but getting data out would be cool too, the example that comes to mind is haptic devices

currently to interface a haptic device to VRC, a user would have to have a local screen space shader that would put colors on the desktop screen to then be read by a screen recording software and beamed to the hardware

the process would be greatly simplified, as well as allow for more local logic for other systems, if the avatar could not only receive, but send OSC messages, is this something that is planned or being considered at all remotely? 

i hope that all makes a bit of sense, thank you for your time 

--Point

**Comment by momo-the-monster** [comment]
@PointDevice - the current system can send [Avatar Parameters out](https://github.com/vrchat-community/osc/wiki/Avatar-Parameters), and we have [a system planned for Haptics](https://github.com/vrchat-community/osc/milestone/3).

We're considering allowing multiple ports in and out, but in the meantime you can use software like [The Wizard of OSC](https://controlmedia.art/) to combine data to a single stream.

**Comment by PointDevice** [comment]
ah, perfect, thank you for the response on this, that makes this whole system much more featured than i expected when initially announced, keep up the good work!
