### ISSUE TITLE
Issues with Parameters and Avatar Names with non-alphanumeric characters

### ISSUE THREAD

**Issue by logicmachine** [vrchat-community/osc#31]
**Describe the bug**
Expression parameters that contains whitespaces in its name cannot be modified via OSC input.
According to the debug consoles, it seems that address and value are received normally but expression parameters are not modified.

**To Reproduce**
1. Upload an avatar that has an expression parameter with whitespaces in its name.
2. Send OSC message with address for problematic parameter. (I copied its address from autogenerated JSON.)

**Expected behavior**
Parameter will be modified similar to when its name does not contains whitespaces.

**Screenshots**
![image](https://user-images.githubusercontent.com/1937211/154505569-bdef9d8e-7a64-4984-b190-66a7f7c0327c.png)

**Info (please complete the following information):**
 - Type: Desktop
 - VRChat version: Build 1166

**Comment by momo-the-monster** [comment]
Thanks for reporting - my first thought is that we can replace spaces with underscores when generating the config and matching names. FWIW - you should be able to do this with your existing config - just change the `input.address` in the config to have an underscore while leaving the name of the parameter the same.

**Comment by NarryG** [comment]
> Thanks for reporting - my first thought is that we can replace spaces with underscores when generating the config and matching names. FWIW - you should be able to do this with your existing config - just change the `input.address` in the config to have an underscore while leaving the name of the parameter the same.

There are other characters that don't work as well such as `}`. It's unlikely they're in parameter names, but it would make sense to either replace all of them, even if they're not likely to be used.  
I can see the utility in the ability to intentionally ensure OSC can't be used against an avatar (e.g. people who use pincode systems on their avatars so they can share them public with friends but random people can't use it if they close it) can't be bruteforced, but it is somewhat edge case.

**Comment by momo-the-monster** [comment]
@NarryG - agreed on the sanitation approach. I think we'll replace every non-alphanumeric character with either nothing or an underscore.

**Comment by momo-the-monster** [comment]
Fixed in next release! Any non-alphanumeric characters will be replaced with underscore. You can patch this yourself in the meantime by replacing them yourself in the config.

So a Boolean parameter named "Toggle With Space" can be modified to:
```
{
    "name" : "Toggle With Space",
    "input" : {
        "address" : "/avatar/parameters/Toggle_With_Space",
        "type" : "Float"
    },
    "output" : {
        "address" : "/avatar/parameters/Toggle_With_Space",
        "type" : "Bool"
    }
}
```
