### ISSUE TITLE
Send the new avatar ID on avatar switch

### ISSUE THREAD

**Issue by benaclejames** [vrchat-community/osc#5]
### Discussed in https://github.com/vrchat-community/osc/discussions/3

<div type='discussions-op-text'>

<sup>Originally posted by **benaclejames** February 17, 2022</sup>
This would help avoid sending/processing unnescessary data when it's unneeded. Programs could reference the config file entry for said avatar ID to know what needs to be processed </div>

**Comment by bdunderscore** [comment]
Note that the config file path contains the avatar _name_ as well as ID, so it would be ideal to also have an OSC path that presents the full config file path on avatar change.

**Comment by benaclejames** [comment]
The new avatar load endpoints looking awesome so far! I'd still reccommend adding an input to get the current avatar ID too, just in case the OSC sending application loads after the avatar

**Comment by bdunderscore** [comment]
Overlaps with #51 perhaps?

**Comment by momo-the-monster** [comment]
we now have `/avatar/change` which send the id of a newly-loaded avatar once it's loaded.
