### ISSUE TITLE
Expose an OSC input to control mic toggle

### ISSUE THREAD

**Issue by FrostbyteVR** [vrchat-community/osc#63]
**What's the idea?**
Expose an input `/input/mic` for toggling your mic input (as if you pressed/held the V key).

This will allow turning your mic on/off while being tabbed out of vrchat. Would also allow for custom controllers to have a mic toggle.

**Is there another way?**
Not really, you could emulate keyboard input but that would require vrchat to be the active window; which would not allow for talking in vrchat while being tabbed out of it.

**Comment by brandonvdongen** [comment]
on that note. I've tried to do this through keypress emulation. but for some reason it just doesn't work to emulate the key for vrchat with any library i tried.. vrchat seems to listen only to keyboard V presses virtual v keypresses.

**Comment by momo-the-monster** [comment]
In next build as `/input/voice`
