### ISSUE TITLE
OSC endpoint to request all paramerters

### ISSUE THREAD

**Issue by kb10uy** [vrchat-community/osc#64]
**What's the idea?**
If OSC client application was launched after VRChat, it cannot track parameter changes before.

Providing an endpoint for requesting all parameters will resolve this problem like below:
1. Client application launches after VRChat.
2. Client application sends packet to this endpoint with no arguments.
3. VRChat sends all parameters and their values.

I think OSC packets from VRChat are probably idempotent, so broadcasting the current state is safe.

**Is there another way?**

**Additional context**

**Comment by bdunderscore** [comment]
Duplicate of #51
