### ISSUE TITLE
Japanese string is corrupted.

### ISSUE THREAD

**Issue by soramimi** [vrchat-community/osc#70]
**Describe the bug**

If avatar name includes Japanese character, the report of `/avatar/config` string is wrong

**To Reproduce**

Change to an avatar with Japanese in the name.

**Expected behavior**

Expect the string will not be corrupted.

#### Unicode

日 --- U+65e5
本 --- U+672c
語 --- U+8a9e

#### UTF-8

日 --- E6 97 A5
本 --- E6 9C AC
語 --- E8 AA 9E 

#### Expected

"日本語" -> E6 97 A5 E6 9C AC E8 AA 9E

#### Actual

"日本語" -> E5 2C 9E

**Screenshots**

![image](https://user-images.githubusercontent.com/3043124/155257389-f7c61ce1-bcbc-4336-ade0-d7a90d51e8f0.png)

![image](https://user-images.githubusercontent.com/3043124/155259074-c02f1fe1-dd66-44f8-b5cc-ecde10b145b8.png)

**Comment by bdunderscore** [comment]
I'll note that according to the OSC specs, the string datatype is specifically an ASCII string. As such, paths will probably need to be passed as a blob type.

**Comment by NarryG** [comment]
> I'll note that according to the OSC specs, the string datatype is specifically an ASCII string. As such, paths will probably need to be passed as a blob type.

Based on [this commit](https://github.com/vrchat-community/osc/commit/b83cd3261bff7075f2b5b4c28da0d3bdab1198a2), the /avatar/config endpoint is being removed and instead they'll just be using the avatar ID. 
This works around this specific issue, and will just have to be a design consideration going forward.

**Comment by momo-the-monster** [comment]
Currently planning to remove the /avatar/config output while we work through the issues with this approach. An alternative would be to output the path relative to the PersistentData directory, which should only be ASCII characters. So VRChat would send the string `OSC\usr_xxxxxxxx-xxxx\Avatars\avtr_xxx_xxxxx_xxxxx.json` to the address `/avatar/configPath`, and an external tool could combine that with the root of the user's VRChat persistent data directory. This way, paths with possible non-ASCII characters are avoided, and if the path to config data changes in the future, this endpoint will still report correctly.

However - this does not properly send config information for Build & Test avatars (whose configs are not written to disk).

**Comment by NarryG** [comment]
> Currently planning to remove the /avatar/config output while we work through the issues with this approach. An alternative would be to output the path relative to the PersistentData directory, which should only be ASCII characters. So VRChat would send the string `OSC\usr_xxxxxxxx-xxxx\Avatars\avtr_xxx_xxxxx_xxxxx.json` to the address `/avatar/configPath`, and an external tool could combine that with the root of the user's VRChat persistent data directory. This way, paths with possible non-ASCII characters are avoided, and if the path to config data changes in the future, this endpoint will still report correctly.
> 
> However - this does not properly send config information for Build & Test avatars (whose configs are not written to disk).

While this solves this specific issue, this doesn't resolve that you cannot send messages to an avatar parameter containing UTF-16.

**Comment by bdunderscore** [comment]
> Currently planning to remove the /avatar/config output while we work through the issues with this approach. An alternative would be to output the path relative to the PersistentData directory, which should only be ASCII characters. So VRChat would send the string `OSC\usr_xxxxxxxx-xxxx\Avatars\avtr_xxx_xxxxx_xxxxx.json` to the address `/avatar/configPath`, and an external tool could combine that with the root of the user's VRChat persistent data directory. This way, paths with possible non-ASCII characters are avoided, and if the path to config data changes in the future, this endpoint will still report correctly.
> 
> However - this does not properly send config information for Build & Test avatars (whose configs are not written to disk).

Ah, that certainly makes more sense if you're planning on replacing `/avatar/config` with one that can be controlled to not include unicode. Note of course that the avatar name needs to be either removed from the config path or sanitized in this case.
