### ISSUE TITLE
Sending OSC at > 10Hz and switching avatars stops parameter updates.

### ISSUE THREAD

**Issue by benaclejames** [vrchat-community/osc#76]
**Describe the bug**
Sending OSC at > 10Hz and switching avatars seems to cause an issue with the part of OscServer that actually sets avatar parameters. I initially thought this was a problem with my implementation, but I can still see the messages/bundles being recieved in the OSC debug window and the parameters don't actually get sent to the currently posessed avatar.

**To Reproduce**
Send OSC roughly every 10ms and switch avatar. Can be seen with my [Face Tracking implementation](https://github.com/benaclejames/VRCFaceTracking). The issue will still occur even without any face tracking hardware connected.

**Expected behavior**
The avatar parameters should continue to update after the switch has finished.

**Screenshots**
Attached are the logs. The OscServer errors get spammed as soon as the avatar is switched.
[output_log_19-15-04.txt](https://github.com/vrchat-community/osc/files/8135188/output_log_19-15-04.txt)

**Info (please complete the following information):**
 - Desktop
 - 2022.1.1 1169

**Comment by benaclejames** [comment]
Further investigation shows this only happens after osc parameters have been "declared" by sending them for the first time. Switching out of the avatar while these new parameters are being sent causes the error to start. 
It seems pausing the osc sender, switching avatar, and re-enabling it seems to stop the errors. A way to tell when the switch avatar button has been initially pressed and a new avatar has started loading would temporarily fix this problem as any OSC programs could pause sending during this loading period

**Comment by seanedwards** [comment]
I think I encountered this yesterday, and after an avatar reset, I started receiving messages again. I wasn't doing a lot of testing though, I only did it once, so consider this an anecdote rather than a workaround. Even so, might be worth another test if someone is running into this issue.

**Comment by benaclejames** [comment]
Odd, resets of both the avatar and osc don't seem to help in this case unfortunately...

Just quadrouple checked this isn't an issue with my implementation by using protokol and sending the avatar switch osc message via a python script and it seems to have no issues parsing the messages 🤷‍♂️
![image](https://user-images.githubusercontent.com/11042095/155811829-f3b28999-f02d-4eed-a38d-c426ac8b1c91.png)

**Comment by benaclejames** [comment]
So after some further debugging, I know exactly why this happens and how to fix it. It's unfortunately something that needs to be implemented on VRChat's side though. 

## The Cause
It comes from the MainThreadQueue inside OSCServer not being reset on avatar switch. The actions being added to that thread queue have the chance of staying around even after an avatar switch, and if one of those actions throws an exception (I'm guessing caused by a nullref of an unloaded avatar), the execution queue loop stops early, so it never gets to reset itself.

## The Tested Fix
Once the avatar has unloaded, make sure to set the m_MainThreadCount to zero and set the m_MainThreadQueue to a new Action array of size 16. This clears up any remnant delegates and has been proven to work already. That or check for null refs in the class you're delegates are targeting.

Thanks for coming to my ted talk

**Comment by momo-the-monster** [comment]
Fixed in VRChat 2022.1.1p5
